///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SomeRootEntityList {
/*
{
  "router_name": "滑动+缩放 过度",
  "router_widget": "SliderScaleRoute"
} 
*/

  String routerName;
  String routerWidget;

  SomeRootEntityList({
    this.routerName,
    this.routerWidget,
  });
  SomeRootEntityList.fromJson(Map<String, dynamic> json) {
    routerName = json["router_name"]?.toString();
    routerWidget = json["router_widget"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["router_name"] = routerName;
    data["router_widget"] = routerWidget;
    return data;
  }
}

class SomeRootEntity {
/*
{
  "list": [
    {
      "router_name": "滑动+缩放 过度",
      "router_widget": "SliderScaleRoute"
    }
  ]
} 
*/

  List<SomeRootEntityList> list;

  SomeRootEntity({
    this.list,
  });
  SomeRootEntity.fromJson(Map<String, dynamic> json) {
  if (json["list"] != null) {
  var v = json["list"];
  var arr0 = List<SomeRootEntityList>();
  v.forEach((v) {
  arr0.add(SomeRootEntityList.fromJson(v));
  });
    list = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (list != null) {
      var v = list;
      var arr0 = List();
  v.forEach((v) {
  arr0.add(v.toJson());
  });
      data["list"] = arr0;
    }
    return data;
  }
}
